name: dls_s600
description: A Flutter plugin by Dolly Solutions for S600 device functionality including printing, QR codes, and smart card operations.
version: 1.0.0
publish_to: 'https://pub.dev'

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dollysolutions.s600
        pluginClass: DlsS600Plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/dpark-logo-new.png
    - assets/canvas.bmp

# ✅ เพิ่ม config สำหรับ flutter_launcher_icons ด้านล่างนี้
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
