name: dls_s600
description: A Flutter plugin by Dolly Solutions for S600 device functionality including printing, QR codes, and smart card operations.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  image: ^4.1.3 # หรือเวอร์ชันล่าสุด
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dpark-logo-new.png
    - assets/canvas.bmp
  plugin:
    platforms:
      android:
        package: com.dollysolutions.s600
        pluginClass: ThaiIdCardReaderPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ✅ เพิ่ม config สำหรับ flutter_launcher_icons ด้านล่างนี้
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
homepage: https://carparkcenter.com
repository: https://github.com/pawit2008/flutter_plugin_s600
